### ISSUE TITLE
Major milestones to be done before next deploy (11 March)

### ISSUE THREAD

**Issue by Lavhe** [JMRSquared/CoPortal#25]
> @Lavhe 
- [ ] Download notes as PDF
- [ ] Share notes via the app
- [ ] Add timetable by lecturer on website
- Any required API call

> @netshedzo 
- [ ] Handle lecturer login
- [ ] Send notification to students by lecturer
- [ ] 

> @terrenceilidio 
- [ ] Student list view when logged in as lecturer
- [ ]
