### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Lavhe** [JMRSquared/CoPortal#6]
- [ ] Align the cards on the landing page
- [ ] Remove Test List from the home page
- [ ] Rename marksheet to `Assessment results`

**Comment by Lavhe** [comment]
- [ ] Send notification pop-up scrolling

**Comment by netshedzo** [comment]
can you name the "Remove useless staff from the ModuleVIew.vue" to be removed

**Comment by netshedzo** [comment]
Was the "my profile card" router already created and where is it?

**Comment by Lavhe** [comment]
Sorry for the late reply 

1.I had delete the Profile Card soo its cool
2.I will remove the useless staff from the ModuleView.vue
